### ISSUE TITLE
感觉传递参数args有些问题

### ISSUE THREAD

**Issue by targeral** [Selection-Translator/chrome-call#1]
看了源码的实现，对于某一个对象方法传递的参数，如果是数组的话（超过一个元素数量，比如两个字符串["key1", "key2"]），源码里直接将回调加到了数组里，这样会报错。因为对于某一个对象方法的第二个参数应该是个回调函数，结果是个字符串。如下：

``` js
object[methodName].apply(object, ['key1', 'key2', callback])
```

所以我使用的时候，就不得不这样搞了：

``` js
const items = await chromeCall(chrome.storage.local, 'get', [[
          "key1",
          "key2"
]]);
```

您看一下是不是要改一下这里的处理 (～￣▽￣)～。

**Comment by lmk123** [comment]
嗯，是会有这个不方便的地方。当初之所以这么设计是因为第四个参数要传一个 boolean 值来判断 Promise 要不要返回一个数组：

```js
// 第四个参数传了个 true
chromeCall(chrome.storage.local, 'get', [['key1', 'key2']], true).then(args => {
  Array.isArray(args) // true
})
```

由于一个 boolean 占用了这第四个参数，所以只能将方法自身的参数用数组组织起来全塞进第三个参数里了，现在看来这不是一个好的设计。

其实可以用第一个参数来做判断，如果是 true 就返回数组，如果第一个参数是 false 或者不是 boolean 就按照一般的方式返回：

```js
// 第一个参数传了个 true
chromeCall(true, chrome.storage.local, 'get', ['key1', 'key2']).then(args => {
  Array.isArray(args) // true
})

// 第一个参数传了个 false
chromeCall(false, chrome.storage.local, 'get', ['key1', 'key2']).then(args => {
  Array.isArray(args) // false
})

// 或者第一个参数不传 boolean
chromeCall(chrome.storage.local, 'get', ['key1', 'key2']).then(args => {
  Array.isArray(args) // false
})
```

改动应该不是很大，你可以提个 PR，或者等我这个周末看看有没有空改 😂

**Comment by lmk123** [comment]
v4.0.0 改成 `chromeCall(chrome.storage.local, 'get', ['key1', 'key2'])` 这种写法了。
